name: test with NODE_DEBUG

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Phala Cloud
        uses: Leechael/phala-deploy-action@86bd1aef1e29a3d66601902388fcbe8e8d117f1e
        with:
          phala-api-key: ${{ secrets.PHALA_CLOUD_API_KEY }}
          app-id: 77827dda2e3e21fad5de8f17a87e3fc494b34c0e
          envs: |
            FOO: BAR
            BAR: BAZ
