name: deploy test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Phala Cloud
        uses: Leechael/phala-deploy-action@e4d6182b6eabb002b4b507764d1a9b36648177ed
        with:
          phala-api-key: ${{ secrets.PHALA_CLOUD_API_KEY }}
          app-id: dc6b7e1155a4d9bf619b0475466fb7e7f9397060